version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - DEBIAN_FRONTEND=noninteractive
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - .:/scormplayer